# Generated by Django 3.2 on 2023-08-09 19:14

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_favorite_unique_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(default='#E1C4FF', image_field=None, max_length=18, samples=None),
        ),
    ]
